//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBasePostulantes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        public int ExperienciaLaboralId { get; set; }
        public string NombreEmpresa { get; set; }
        public string Puesto { get; set; }
        public int TiempoLaborado { get; set; }
        public string MotivoRenuncia { get; set; }
        public string NombreReferencia { get; set; }
        public Nullable<int> CelularReferencia { get; set; }
        public int FichaDatosId { get; set; }
    }
}
