//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBasePostulantes
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaDatos
    {
        public int FichaDatosId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string DNI { get; set; }
        public int Celular { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string Distrito { get; set; }
        public string Departamento { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public string PuestoInteresado { get; set; }
        public string GradoInstruccion { get; set; }
        public string CentroEstudiosSuperiores { get; set; }
        public Nullable<int> Ciclo { get; set; }
        public string EstudiosComplementarios { get; set; }
    }
}
